### ISSUE TITLE
ajax callback(success:function(){})

### ISSUE THREAD

**Issue by qq377751971** [gonzalocasas/jquery-aop#15]
Hi,I hava a problem.How to add aop.before to ajax's success callback method.

**Comment by gonzalocasas** [comment]
I assume you're using jQuery's ajax, in that case, why not use the callback provided by jquery itself? http://api.jquery.com/ajaxsuccess/

**Comment by gonzalocasas** [comment]
@qq377751971: ok, I assume my previous comment solved your need, so I'll close this. If not, then let me know.

**Comment by qq377751971** [comment]
I know how to do it.Thank you very much!
